### ISSUE TITLE
Contains key fail: unexpected AST node: ( 

### ISSUE THREAD

**Issue by MiguelAngelLV** [alexliesenfeld/querydsl-jpa-postgres-json#1]
```
org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected AST node: ( near line 3, column 25 [select book from  models.Book book
where hql_jsonb_contains(book.tags,?1)]
```

The query:

```kotlin
    val q = BooleanBuilder()
    val json = JsonPath.of(QBook.book.tags)
    tags?.forEach {
            q.and(json.contains(it))
        }
```

Works fine with 

```kotlin
        tags?.forEach {
            q.and(json[it].asText().isNotEmpty)
        }
```

The model:

```kotlin
@Entity
@Table(name = "books")
@TypeDefs(TypeDef(name = "jsonb", typeClass = JsonBinaryType::class))
class Book  {

    @Id
    var id: Long = 0
    var name: String = ""

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    var tags = HashMap<String, Any>()

}

```

**Comment by hunter-read** [comment]
The syntax of spatial functions requires you to test the function against a boolean value in hibernate so `where hql_jsonb_contains(book.tags,?1)` needs to be `where hql_jsonb_contains(book.tags,?1) = true`

**Comment by alexliesenfeld** [comment]
@MiguelAngelLV Can you confirm pull request #2 fixes your issue? It was merged and released with [v0.0.7](https://github.com/alexliesenfeld/querydsl-jpa-postgres-json/releases/tag/v0.0.7).

**Comment by MazurOlha** [comment]
> The syntax of spatial functions requires you to test the function against a boolean value in hibernate so `where hql_jsonb_contains(book.tags,?1)` needs to be `where hql_jsonb_contains(book.tags,?1) = true`

Thanks a lot!!! I have been searching your answer for ages!!!

**Comment by AhmadAlhajKarim** [comment]
I would recommend you to set the property nativeQuery to **true**

```
@Query(value = "SELECT t.id FROM team as t JOIN project AS p ON p.team_id",
 nativeQuery = true)

```
